### ISSUE TITLE
Eng/UX agree on how to conceptualize ScreenContentSection and subsections

### ISSUE THREAD

**Issue by knipec** [techmatters/terraso-mobile-client#1288]
## TODO
- [ ] Agree on a design for components on the relevant screens
- [ ] Implement the component, use them on the relevant screens
- [ ] Add the component to the components page that will be in Figma 

### Relevant screens for Capri:
- Soil ID (and selected soil variant)
- Site Slope Steepness
- Site Soil Texture
- Site Soil Color (main & photo)

## Context
Based on this discussion in [PR 1265](https://github.com/techmatters/terraso-mobile-client/pull/1265#discussion_r1596041385):
  **Option 1**: (what exists currently)
  - ScreenContentSection with title="Soil ID"
  - ScreenContentSection for Soil Matches with grey background
  - ScreenContentSection with title="Site Data"
  
  **Option 2**: 
  - One-off SoilIdSection component that exists mostly just for conceptual reasons
      - ScreenContentSection with title="Soil ID"
      - ScreenContentSection for Soil Matches with grey background
  - ScreenContentSection with title="Site Data"
  
  **Option 3** (I think this is closest to Courtney's mental model, but feels slightly over-engineered for right now?):
  - ScreenContentSection with title="Soil ID" (it will render its children with alternating white and gray backgrounds, and give the title heading and each child the same padding)
      - Description
      - TopSoilMatchesSection
  - ScreenContentSection with title="Site Data"

**Misc**
- One piece of complexity is that the sub-sections should get background color that goes all the way to the edges, so padding cannot be done it . 
- Also want to confirm with Courtney that Option 3 does indeed match the design spec.

**Comment by shrouxm** [comment]
@knipec do you know if this is still relevant?

**Comment by knipec** [comment]
Checking in with @CourtneyLee333 about this: If our existing component seems good, shall we add it to the component library and close this task?

Currently we have a `ScreenContentSection` component in code, but I don't think it's yet in the Component Library [Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=7202-34072&p=f&t=SEhkW6Q5SEWPBtps-0). 
It takes as props:
- title (as a string, optionally -- which it will put as a variant h4 Heading)
- backgroundColor (as a string, optionally)
- children components (the contents to go in the section)
And it will basically just put a box with the contents, and standardized vertical and horizontal padding

Each section outlined in purple is a `ScreenContentSection` with the properties listed in purple:
![Image](https://github.com/user-attachments/assets/2433439e-bc45-41f1-8656-343165e0d06b)
