### ISSUE TITLE
Site screens need correct background colors

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-mobile-client#1601]
We need to check the following places and make sure the background colors are correct:

```[tasklist]
### Tasks
- [x] Dashboard screen - white
- [x] Tab slider -grey/200
- [x] Slope screen - grey/300
- [x] Soil screen - grey/300
```

**Comment by CourtneyLee333** [comment]
Looks good, thanks!
