### ISSUE TITLE
Demo small bugs

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-mobile-client#223]
Several small bugs came up in the demo:

```[tasklist]
### Tasks
- [x] Text "Map" needs to be changed to "Home" on the bottom bar
- [x] Create Site screen has both a back button and a X close button. The back button should be removed.
- [x] Project title should change on update
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/412
```

**Comment by david-code** [comment]
Closed and made a separate issue: https://github.com/techmatters/terraso-mobile-client/issues/223
