### ISSUE TITLE
Styling Feedback: for Transfer Sites workflow (Project view)

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#570]
Updates to the experience for transferring sites to projects (from the project view)

## To find this screen
1. Open a project where you are a manager
2. Select the "Sites" tab
3. Select "Transfer Sites"

## References
[See Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=165-21734&mode=design&t=580ptJMKveswYvCR-0)

Courtney's feedback can be found across two docs - [this one](https://docs.google.com/document/d/1YI5rUzbHHMHii0uDE_JEF411NaEezoL7wKN1rVAfBOU/edit#heading=h.qmca1vieip6u) and [this one](https://docs.google.com/document/d/1mnFPTAO0jrYgI0A-pxqGxKGmCzyD3qC7UxVzBAEYZOw/edit?usp=sharing).

```[tasklist]
### Tasks
- [x] Main sites tab showing empty state or list of site cards background should be grey/300
- [ ] iOS checkboxes should be consistent
- [x] Transfer Sites screen with list of possible sites for transfer needs white background
- [x] Text description “Transfer LandPKS sites you manage to this project. When you transfer sites, they will use the data settings and team member roles from this project.”
- [x] disabled button styling: button color #E0E0E0
- [x] disabled button styling: Text Color #1A202C 38%
- [x] disabled button styling: remove drop shadow
- [x] Accordion headers should have 1px margin or border between them when closed.
```

iOS checkboxes
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/24b5369d-f6d1-408b-bc4d-6d63b72ae9b4" width="400px">

**Comment by CourtneyLee333** [comment]
@ltseng The issue description is incorrect. The guiding principle here is that the screen background is grey when we will be showing site or project cards on it - the cards are white, so the grey background helps provide contrast to differentiate each card. So the first two items in your list should be:

- Main sites tab showing empty state or list of site cards background should be grey/300
-Transfer Sites screen with list of possible sites for transfer needs white background 

Tooltip text was updated in the content audit since the document you linked. It should be "When you transfer sites, they will use the data settings and team member roles from this project."

Disabled button also needs the correct word: Transfer. 

It might be better to link to my most recent QA document to avoid confusion:
https://docs.google.com/document/d/1mnFPTAO0jrYgI0A-pxqGxKGmCzyD3qC7UxVzBAEYZOw/edit?usp=sharing

**Comment by ltseng** [comment]
Paul has expressly requested that I copy the exact changes to be made into the issue body itself instead of linking documents. I have made your edits to the issue description above though, thank you!

**Comment by CourtneyLee333** [comment]
On iOS:
- Check boxes are still circles instead of squares, but I'm okay with that if circles are implemented throughout the rest of the iOS UI. 
On iOS and Android:
- Button doesn't match the feedback, but let's save it for the bigger button component sweep so I can get clear on all the styles.
- There is still no margin between accordion headers.

**Comment by paulschreiber** [comment]
This can be verified in 160.

**Comment by DerekCaelin** [comment]
@paulschreiber In 160, the checkboxes are still circles.

**Comment by CourtneyLee333** [comment]
Looks good, thanks!
