### ISSUE TITLE
Update styling and content for Data Privacy info sheet

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#716]
Update the styling of links on the Data Privacy info screen, using the component designed as a part of #954 

## Design
[Data Privacy info sheet](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3809%3A67973&mode=design&t=dndvQF8yefLoHf3X-1)

## Steps to find screen
1. Open app
2. Log in
3. Navigate to a site
4. In the "Details" section, select (i) button next to "Data Privacy"

## Additional Context
- Dependent on #954 
- See [Links notes for engineers](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2647%3A10445&mode=design&t=dndvQF8yefLoHf3X-1)
- This is a companion engineering issue to https://github.com/techmatters/terraso-product/issues/454

## Acceptance Criteria

```[tasklist]
### Tasks
- [ ] Privacy Policy should link to: https://techmatters.org/privacy-policy/
- [ ] Remove language: public sites are visible to anyone on the LandPKS data portal. This means anyone can view information about this site.
- [ ] Remove link to data portal
- [ ] Bug: X doesn't doesn't close the data privacy sheet
- [ ] All links on the data privacy info sheet use the component design as a part of #954
- [ ] Data Privacy label should be bigger (body 1 and bold)
- [ ] Data Privacy icon should be the correct color
- [ ] The Data Privacy should leave space at the top to see the Header, as per [this design](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=138-13384&mode=design&t=9GsDx5X5o360WdEc-0)
```

**Comment by CourtneyLee333** [comment]
@knipec I don't think this issue is necessary any more. Some parts are irrelevant, and others are covered by #755 .

**Comment by knipec** [comment]
Closing per Courtney's comment above. 
FYI @DerekCaelin
