### ISSUE TITLE
Update home screen app bar info sheet content and styling

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#801]
Update the info sheet on the home screen to match the content of the current design. 

## Design
FYI: 
- Don't actually include the "Access the Web Portal" part 
- LandPKS Data Privacy has the link styled, but the icon and text are flipped. Flipping them to align with the design could be part of #954 or this. 

[Here is the Figma reference](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2066%3A93125&mode=design&t=8NJ6UFjDXUEKnYJl-1) (also copied below for quick reference)

<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/b132f81e-6ec7-4a50-ae60-65aaa1bc103d" width="300px">

## Steps to find the info sheet
1. Log in to app
2. Go to home screen
3. Tap the (i) icon on the top left'

## Additional context re styling

- See [Links notes for engineers](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2647%3A10445&mode=design&t=dndvQF8yefLoHf3X-1)
- Dependent on: https://github.com/techmatters/terraso-mobile-client/issues/954
- This is the companion engineering task to https://github.com/techmatters/terraso-product/issues/454

## Acceptance criteria

```[tasklist]
### Tasks
- [x] Update the icon to match our new branding. [The new graphic is in Drive here.](https://drive.google.com/file/d/158mCOPKV063u6kge65llrIEEclCbem3k/view?usp=drive_link)
- [x] The text "Gain insights" should be its own sentence, instead of part of another sentence
- [x] Numbered list should start with "1" (currently starts with "2")
- [x] The text of the numbered list needs to be updated, particularly in number 2
- [x] Add links to LandPotential.org
- [x] Properly style the external links (See issue #954)
```

**Comment by ltseng** [comment]
Also make sure that on different devices, lines aren't being cut off in the 2nd and 3rd bullet point
<img src="https://github.com/techmatters/terraso-mobile-client/assets/2730009/65ae9cd1-0c5e-47c1-a3a1-5490b4b72d35" width="300">

**Comment by knipec** [comment]
This should be verifiable in v119

**Comment by DerekCaelin** [comment]
Thanks for this @knipec! Closing the issue, and we'll do QA in may: https://github.com/techmatters/terraso-product/issues/735
