### ISSUE TITLE
Implement info icons and help text for slope and soil texture/rock fragments

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-mobile-client#853]
The text content is way too long to paste directly into this Github issue. Please refer to the designs ([slope](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1848-49976&mode=design&t=hCP37jSStRTaOsF6-0) and [soil texture/rock fragments](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=1850-50163&mode=design&t=hCP37jSStRTaOsF6-0) themselves for the text, and keep in mind that different text may be triggered by different UI elements. Check with me or Courtney if you have any questions at all!
```[tasklist]
### Tasks
- [x] Slope info sheet (Go to the slope data input screen and hit the info icon next to the word "Slope." The info icon is there, but doesn't open a bottom sheet yet)
- [x] Slope meter info sheet (Go to slope data input and hit slope meter button. The info icon is there, but doesn't open a bottom sheet yet) -- Note: Phone will be in landscape mode
- [x] Soil texture info sheet (Go to soil tab of site dashboard and tap on any soil texture or rock fragments row. The info icon is next to the words "Soil Texture" but doesn't currently open a bottom sheet)
- [x] Rock fragment volume info sheet (Go to soil tab of site dashboard and tap on any soil texture or rock fragments row. The info icon is next to the words "Rock Fragments" but doesn't currently open a bottom sheet)
- [x] Slope shape info sheet (include PNG images. Maybe someday they will be SVG with #1114)
```

**Comment by knipec** [comment]
This will be verifiable in build v118

**Comment by CourtneyLee333** [comment]
Nice work @knipec ! Passes my QA on Android and iOS, with one comment:
- The sheets are varying in how tall they are and how much padding is at the bottom. This is not a big deal for Capri, but would be nice to make consistent per Notes for Engineers.

**Comment by DerekCaelin** [comment]
Thanks, Courtney. @knipec this is cleared to push to main, nice work. 👍

**Comment by knipec** [comment]
@DerekCaelin With the mobile product, we push changes to main, and then they go into a build that you can verify (assuming you don't have a dev environment set up for verification). So this has already been pushed to main with [PR 1134](https://github.com/techmatters/terraso-mobile-client/pull/1134) :) Let me know if you have questions about this workflow though!

@CourtneyLee333 Ah, makes sense! Is there a GitHub issue for that to track that future work? If not, let me know if you'd like me to make one.

**Comment by DerekCaelin** [comment]
@knipec please make an issue for the future work! I'll mark this as done.

**Comment by CourtneyLee333** [comment]
@DerekCaelin There was a ticket about overlay sheet styles, but I think that one might be closed? It would be ideal if the behaviors and styles were implemented in the component itself, rather than needing to be tweaked on each instance. The design tweaks on this ticket seem to be closely related to https://github.com/techmatters/terraso-product/issues/737. Should we add the detail there, or somewhere else?

**Comment by knipec** [comment]
@CourtneyLee333 Agree that they seem pretty related, I'll add it to https://github.com/techmatters/terraso-product/issues/737 !
